# Data Reforming Test Ground

This Jupiter notebook is here to test the exercise regarding data fromatting.


Import all libraries and load the data set

In [1]:
# Enable autoreloading of imported modules
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import sys
import os
import pandas as pd
from courselib.utils.splits import train_test_split

# Add the repo root (two levels up from this notebook) to sys.path
sys.path.insert(0, os.path.abspath("../../"))

In [2]:
file_name = "adult.data"
column_names = column_names = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education-num",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country",
    "Class"
]
df = pd.read_csv(file_name, names= column_names,skipinitialspace=True)
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Class
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

## Analysing the Data set 

### 1) Identify which categorical features are low- or high-cardinality

`"age"`: numerical / continuous, not a categorical feature, cardinality not applicable

`"workclass"`: categorical, 8 categories, low cardinality

`"fnlwgt"`: numerical / continuous, not a categorical feature, cardinality not applicable

`"education"`: categorical, 16 categories, medium cardinality

`"education-num"`: numerical / continuous, not a categorical feature, cardinality not applicable

`"marital-status"`: categorical, 7 categories, low cardinality

`"occupation"`: categorical, 14 categories, medium cardinality

`"relationship"`: categorical, 6 categories, low cardinality

`"race"`: categorical, 5 categories, low cardinality

`"sex"`: categorical, 2 categories, low cardinality

`"capital-gain"`: numerical / continuous, not a categorical feature, cardinality not applicable

`"capital-loss"`: numerical / continuous, not a categorical feature, cardinality not applicable

`"hours-per-week"`: numerical / continuous, not a categorical feature, cardinality not applicable

`"native-country"`: categorical, 41 categories, high cardinality

## 2) Analyze which variables have a meaningful order (e.g., education)

`"age"`: numerical / continuous, natural numeric order exists, but it is not a categorical variable

`"workclass"`: categorical, no meaningful order

`"fnlwgt"`: numerical / continuous, natural numeric order exists, but it is not a categorical variable

`"education"`: categorical, meaningful order exists
possible order: Preschool < 1st-4th < 5th-6th < 7th-8th < 9th < 10th < 11th < 12th < HS-grad < Some-college < Assoc-voc < Assoc-acdm < Bachelors < Masters < Prof-school < Doctorate

`"education-num"`: numerical / continuous, meaningful order exists, and it already represents the order of education levels

`"marital-status"`: categorical, no meaningful order

`"occupation"`: categorical, no meaningful order

`"relationship"`: categorical, no meaningful order

`"race"`: categorical, no meaningful order

`"sex"`: categorical, no meaningful order

`"capital-gain"`: numerical / continuous, natural numeric order exists, but it is not a categorical variable

`"capital-loss"`: numerical / continuous, natural numeric order exists, but it is not a categorical variable

`"hours-per-week"`: numerical / continuous, natural numeric order exists, but it is not a categorical variable

`"native-country"`: categorical, no meaningful order

## 3) Implement and compare the different encoding methods
See below or the respective Jupiter notebooks

## 📚 Formatting the data set
The goal of this section to find valid data set format which has no strings in them and only consists of numerical elements. The final product should be the input of `train_test_split` and return a welldefined object which can be used for the models.
The target variable should be however always of this format:

$$
y =
\begin{cases}
1 & \text{if income } > \$50K \\
0 & \text{otherwise}
\end{cases}
$$

### 1st Data set proposition 

Here is what happens with each column:

`"age"`: stays as it is

`"workclass"`: make for each category within this column a own column with 0-1 encoding (ie no-yes)

`"fnlwgt"`: drop

`"education"`: drop (is represented by the next feature)

`"education-num"`: stays as it is

`"marital-status"`: make for each category within this column a own column with 0-1 encoding (ie no-yes)

`"occupation"`: make for each category within this column a own column with 0-1 encoding (ie no-yes)

`"relationship"`: make for each category within this column a own column with 0-1 encoding (ie no-yes)

`"race"`: make for each category within this column a own column with 0-1 encoding (ie no-yes)

`"sex"`: just transform with Female = -1, Male =1

`"capital-gain"`: stays as it is

`"capital-loss"`: stays as it is

`"hours-per-week"`: stays as it is

`"native-country"`: make for each category within this column a own column with 0-1 encoding (ie no-yes)

Note: `"capital-gain"` and `"capital-loss"` were considered to be dropped (maybe they will be in another dataframe), however, they may contain strong income-related information.
Fe., someone with a large capital gain probably has investments or assets which often correlates with higher income/wealth. So the model may use it as a strong signal.

How to handle `?` in some lines (here are some ideas i have): 

Option 1: delete lines with unkown data
Option 2: use unknown as its own category for categorical data, but delete rows with unknown data in numerical data.
Option 3: using the weights (which i will drop) find the must likely element which should be in there; for numerical data use a rough estimation

In the following i will use Option 1 but each code is written is such way so that it can be used later on for other options.


In the following consider the following methods with der respectice description: one is to fulfill the obejctive "make for each category within this column a own column with 0-1 encoding (ie no-yes)" while still considering whether to make Option 1 or Option 2 from above. and the other brutely gives me the dataset without unknown data.

In [3]:
def category_column_encoder(df,column_to_be_encoded,number_if_True = 1, number_if_False = 0, delete_old_column = False, drop_unknown_data_rows = [] ):
    """takes a pandas dataframe and columns which need to be encoded and creates new column according to the columns categories.
       The rows then get marked wether the row has or has not the column property. 
       outputs then a new edited copy of df.

    Args:
        df (pd.dataframe): just the dataset
        column_to_be_encoded (list): a list of column names form df which need to be encoded
        number_if_True (int, optional): number if the column property applies to the row. Defaults to 1.
        number_if_False (int, optional): number if the column property does not apply to the row. Defaults to 0.
        delete_old_column (bool, optional): Wether the columns form column_to_be_encoded are deleted or not. Defaults to False.
        drop_unknown_data_rows (list, optional): Drops all rows which include the strings which are in this list. Defaults to empty list.
    """
    _df = df.copy()

    row_amount_before = len(_df)

    if drop_unknown_data_rows !=[]:
        for column_name in column_to_be_encoded:
            _df = _df[~_df[column_name].isin(drop_unknown_data_rows)]

    amount_of_rows_deleted = row_amount_before - len(_df)

    _df = _df.reset_index(drop=True)

    row_amount = len(_df)
    
    for i,column_name in enumerate(column_to_be_encoded):
        list_of_categories = [] #for each column we have a list of categories
        
        for j in range(row_amount):
            
            category =_df[column_name][j] #what string does this row have in the column we look at
            
            if category in list_of_categories:
                new_column_name = column_name +"_"+ category
                _df.loc[j, new_column_name] = number_if_True
                
            if category not in list_of_categories:
                
                list_of_categories.append(category)

                new_column_name = column_name +"_"+ category
                _df[new_column_name] = number_if_False  #add new column
                
                _df.loc[j, new_column_name] = number_if_True
                
            if j== row_amount-1: #delete old column if neccessary
                if delete_old_column:
                    _df = _df.drop(columns=[column_name])
    
    print(f"{amount_of_rows_deleted} out of {row_amount_before} were deleted, ie.{(1- amount_of_rows_deleted/row_amount_before)*100}% still remain ")            
    return _df


def drop_unknown_rows(df, drop_unknown_data_rows):
    """Drops all rows which include one of the values in drop_unknown_data_rows in any column.
       outputs then a new edited copy of df.

    Args:
        df (pd.dataframe): just the dataset
        drop_unknown_data_rows (list): Drops all rows which include the strings which are in this list.
    """
    _df = df.copy()

    row_amount_before = len(_df)

    for column_name in _df.columns:
        _df = _df[~_df[column_name].isin(drop_unknown_data_rows)]

    amount_of_rows_deleted = row_amount_before - len(_df)

    _df = _df.reset_index(drop=True)

    print(f"{amount_of_rows_deleted} out of {row_amount_before} were deleted, ie.{(1- amount_of_rows_deleted/row_amount_before)*100}% still remain ")

    return _df

In [4]:
one_hot_columns = [
    "workclass",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "native-country"
]

In [5]:
df_encoded = drop_unknown_rows(df,["?"])
df_encoded = category_column_encoder(df_encoded,one_hot_columns,delete_old_column=True)

2399 out of 32561 were deleted, ie.92.63229016307852% still remain
0 out of 30162 were deleted, ie.100.0% still remain

In [6]:
sex_mapping = {
    "Male": 1,
    "Female": -1,
}

target_variable_map = {
    "<=50K": 0,
    ">50K": 1,
}

columns_to_be_dropped = [
    "fnlwgt",
    "education"
]

In [7]:
df_encoded = df_encoded.drop(columns=columns_to_be_dropped)
df_encoded["sex"] = df_encoded["sex"].map(sex_mapping)
df_encoded["Class"] = df_encoded["Class"].map(target_variable_map)
df_encoded

,age,education-num,sex,capital-gain,capital-loss,hours-per-week,Class,workclass_State-gov,workclass_Self-emp-not-inc,workclass_Private,...,native-country_Outlying-US(Guam-USVI-etc),native-country_Scotland,native-country_Trinadad&Tobago,native-country_Greece,native-country_Nicaragua,native-country_Vietnam,native-country_Hong,native-country_Ireland,native-country_Hungary,native-country_Holand-Netherlands
0,39,13,1,2174,0,40,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,50,13,1,0,0,13,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,38,9,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,53,7,1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,28,13,-1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30157,27,12,-1,0,0,38,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
30158,40,9,1,0,0,40,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
30159,58,9,-1,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
30160,22,9,1,0,0,20,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
30161,52,9,-1,15024,0,40,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
X, Y, X_train, Y_train, X_test, Y_test =  train_test_split(df_encoded, 
                                                           training_data_fraction=0.8, 
                                                           return_numpy=True)

print('Training data split as follows:')
print(f'  Training data samples: {len(X_train)}')
print(f'      Test data samples: {len(X_test)}')

Training data split as follows:
  Training data samples: 24130
      Test data samples: 6032