# Frequency encoding
In this notebook I will explore the Frequency encoding method for every non-numerical feature. More specifically,

`"age"`: stays as it is

`"workclass"`: Frequency encoding

`"fnlwgt"`: drop

`"education"`: Frequency encoding

`"education-num"`: drop as "education" is represented by Frequency encoding

`"marital-status"`: Frequency encoding

`"occupation"`: Frequency encoding

`"relationship"`: Frequency encoding

`"race"`: Frequency encoding

`"sex"`: Frequency encoding

`"capital-gain"`: stays as it is

`"capital-loss"`: stays as it is

`"hours-per-week"`: stays as it is

`"native-country"`: Frequency encoding

Here is the raw data loaded and apply
$$
y =
\begin{cases}
1 & \text{if income } > \$50K \\
0 & \text{otherwise}
\end{cases}
$$
to the data set. Also drop the columns which were stated before

In [34]:
# Enable autoreloading of imported modules
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import sys
import os
import pandas as pd
from courselib.utils.splits import train_test_split

# Add the repo root (two levels up from this notebook) to sys.path
sys.path.insert(0, os.path.abspath("../../"))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [35]:
file_name = "adult.data"
column_names = column_names = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education-num",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital-gain",
    "capital-loss",
    "hours-per-week",
    "native-country",
    "Class"
]
df = pd.read_csv(file_name, names= column_names,skipinitialspace=True)

In [36]:
target_variable_map = {
    "<=50K": 0,
    ">50K": 1,
}

columns_to_be_dropped = [
    "fnlwgt",
    "education-num"
]

In [37]:
df= df.drop(columns=columns_to_be_dropped)
df["Class"] = df["Class"].map(target_variable_map)
df

,age,workclass,education,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,Class
0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

## One-Hot-Encoding method

In [38]:
def Frequency_Encoder(df,column_to_be_encoded, delete_old_column = False, drop_unknown_data_rows = [] ):
    """takes a pandas dataframe and columns which need to be encoded and creates new column called "{oldcolumnname}_freq".
       The new column has then the frequency representation
       outputs then a new edited copy of df.

    Args:
        df (pd.dataframe): just the dataset
        column_to_be_encoded (list): a list of column names form df which need to be encoded
        delete_old_column (bool, optional): Wether the columns form column_to_be_encoded are deleted or not. Defaults to False.
        drop_unknown_data_rows (list, optional): Drops all rows which include the strings which are in this list. Defaults to empty list.
    """
    _df = df.copy()

    row_amount_before = len(_df)

    if drop_unknown_data_rows !=[]:
        for column_name in column_to_be_encoded:
            _df = _df[~_df[column_name].isin(drop_unknown_data_rows)]

    amount_of_rows_deleted = row_amount_before - len(_df)

    _df = _df.reset_index(drop=True)

    row_amount = len(_df)
    
    if type(column_to_be_encoded) == str:
        column_to_be_encoded = [column_to_be_encoded]
    
    for i,column_name in enumerate(column_to_be_encoded):
        
        new_column_name = f"{column_name}_freq"
        counting_dataframe =_df[column_name].value_counts().to_frame().T.reset_index(drop=True) # gives me every catgory and their respective amount with col names of the categories and the 0-th line their respective amount
        
        _df[new_column_name] = _df[column_name].map(counting_dataframe.loc[0] / row_amount)
        
    if delete_old_column:
        _df = _df.drop(columns=column_to_be_encoded)
        
    print(f"{amount_of_rows_deleted} out of {row_amount_before} were deleted, ie.{(1- amount_of_rows_deleted/row_amount_before)*100}% still remain ")            
    return _df

## Formatting the Data Set

### Choose the Columns which need to be encoded

In [39]:
freq_cols = [
    "workclass",
    "education",
    "marital-status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "native-country",
]

### Running the Data though the One-Hot-Encoder

In [40]:
from projectlib.encoding import drop_rows

df_encoded = drop_rows(df,["?"])
df_encoded = Frequency_Encoder(df,freq_cols,delete_old_column=True)

2399 out of 32561 were deleted, ie.92.63229016307852% still remain
0 out of 32561 were deleted, ie.100.0% still remain

In [41]:
df_encoded

,age,capital-gain,capital-loss,hours-per-week,Class,workclass_freq,education_freq,marital-status_freq,occupation_freq,relationship_freq,race_freq,sex_freq,native-country_freq
0,39,2174,0,40,0,0.039864,0.164461,0.328092,0.115783,0.255060,0.854274,0.669205,0.895857
1,50,0,0,13,0,0.078038,0.164461,0.459937,0.124873,0.405178,0.854274,0.669205,0.895857
2,38,0,0,40,0,0.697030,0.322502,0.136452,0.042075,0.255060,0.854274,0.669205,0.895857
3,53,0,0,40,0,0.697030,0.036086,0.459937,0.042075,0.405178,0.095943,0.669205,0.895857
4,28,0,0,40,0,0.697030,0.164461,0.459937,0.127146,0.048156,0.095943,0.330795,0.002918
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,0,0,38,0,0.697030,0.032769,0.459937,0.028500,0.048156,0.854274,0.330795,0.895857
32557,40,0,0,40,1,0.697030,0.322502,0.459937,0.061485,0.405178,0.854274,0.669205,0.895857
32558,58,0,0,40,0,0.697030,0.322502,0.030497,0.115783,0.105832,0.854274,0.330795,0.895857
32559,22,0,0,20,0,0.697030,0.322502,0.328092,0.115783,0.155646,0.854274,0.669205,0.895857
32560,52,15024,0,40,1,0.034274,0.322502,0.459937,0.124873,0.048156,0.854274,0.330795,0.895857

### Test if the Encoded data Runs through the `train_test_split`

In [42]:
X, Y, X_train, Y_train, X_test, Y_test =  train_test_split(df_encoded, 
                                                           training_data_fraction=0.8, 
                                                           return_numpy=True)

print('Training data split as follows:')
print(f'  Training data samples: {len(X_train)}')
print(f'      Test data samples: {len(X_test)}')

Training data split as follows:
  Training data samples: 26049
      Test data samples: 6512